# Generated by Django 4.1.5 on 2023-01-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ip', models.CharField(max_length=40)),
                ('address_family', models.CharField(choices=[('ipv4', 'ipv4'), ('ipv6', 'ipv6')], max_length=4)),
                ('port', models.PositiveIntegerField()),
                ('protocol', models.CharField(choices=[('telnet', 'telnet'), ('ssh', 'ssh'), ('http', 'http'), ('http-telnet', 'http-telnet')], max_length=40)),
            ],
        ),
    ]
